name: language_learning_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  expand_tap_area: ^1.1.1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_tabler_icons: ^1.43.0
  gradient_borders: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
